version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26.0
workflows:
  build:
    jobs:
      - cypress/run:
          yarn: true
          store_artifacts: true
          post-steps:
            - store_artifacts:
                path: cypress/snapshots
